; Copyright © Microsoft Corp.

[Theme]
; Windows - IDS_THEME_DISPLAYNAME_AERO_LIGHT
DisplayName=Tema Não Salvo
ThemeId={312854C0-BD6E-406F-95BA-DFE421038CF5}

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55

[Control Panel\Cursors]
AppStarting=%SystemRoot%\cursors\wait_r.cur
Arrow=%SystemRoot%\cursors\arrow_r.cur
Crosshair=%SystemRoot%\cursors\cross_r.cur
Hand=
Help=%SystemRoot%\cursors\help_r.cur
IBeam=%SystemRoot%\cursors\beam_r.cur
No=%SystemRoot%\cursors\no_r.cur
NWPen=%SystemRoot%\cursors\pen_r.cur
SizeAll=%SystemRoot%\cursors\move_r.cur
SizeNESW=%SystemRoot%\cursors\size1_r.cur
SizeNS=%SystemRoot%\cursors\size4_r.cur
SizeNWSE=%SystemRoot%\cursors\size2_r.cur
SizeWE=%SystemRoot%\cursors\size3_r.cur
UpArrow=%SystemRoot%\cursors\up_r.cur
Wait=%SystemRoot%\cursors\busy_r.cur
DefaultValue=Windows em Preto

[Control Panel\Desktop]
Wallpaper=%USERPROFILE%\Downloads\de84q9u-2beec4a4-87d6-44b6-a0f6-967ee276dda0 (1).png
Pattern=
MultimonBackgrounds=0
PicturePosition=4

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC4FF1E0B
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=@mmres.dll,-800

[Theme.A]
DisplayName=Tema Não Salvo
[Theme.W]
DisplayName=Tema N+AOM-o Salvo
